#GAME SPEED MODES
SLOW = 0.2
NORMAL = 0.1
FAST = 0.05

#SNAKE SHAPE MODES
SQUARED = "square"
CIRCLED = "circle"

#FOOD SIZE MODES
SMALL = 0.5
BIG = 1

### CONFIG ###
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800
BACKGROUND_COLOR = "black"
GAME_SPEED = NORMAL
SNAKE_SHAPE = SQUARED
SNAKE_COLOR = "white"
FOOD_SIZE = SMALL
FOOD_COLOR = "red"
### CONFIG END###
